# Copyright Epic Games, Inc. All Rights Reserved.
"""Tests for DemoPythonToolSet."""

import json

import unreal

from toolset_registry.tests.demo_toolset import DemoPythonToolset
from toolset_registry.tests.toolset_testcase import DemoToolsetTestCase

DEMO_TOOLSET_NAME = f'{DemoPythonToolset.__module__}.{DemoPythonToolset.__name__}'


class TestDemoToolset(DemoToolsetTestCase):
    """Tests for the DemoPythonToolset, an example toolset written in Python."""

    def test_toolset_name(self):
        """Test that toolset name is properly generated.

        Name should match what is generated by
        FToolsetLibraryWrapper::GetToolsetClassName from the class metadata.

        """
        # Get toolset name as generated by FToolsetLibraryWrapper.
        registry = unreal.ToolsetRegistry
        schema_string = registry.get_toolset_json_schema(DemoPythonToolset)
        schema = json.loads(schema_string)
        toolset_name = schema['name']

        uclass = DemoPythonToolset.static_class()
        class_name = uclass.get_name()
        package_name = uclass.get_outer().get_name()

        toolset_name_parts = toolset_name.split('.')
        self.assertTrue(len(toolset_name_parts) > 1)
        package_parts = package_name.split('/')
        self.assertTrue(len(package_parts) > 1)

        # Check that last part of toolset_name is the class name.
        self.assertEqual(toolset_name_parts[-1], class_name)
        # Check that second-last part of toolset_name is the python file with
        # '_PY' stripped off.
        self.assertEqual(toolset_name_parts[-2] + '_PY', package_parts[-1])
        # Check that namespacing parts of the toolset name are in package path
        # in the same order.
        toolset_qualifier_sublist_repr = '/'.join(toolset_name_parts[0:-1])
        self.assertTrue(package_name.find(toolset_qualifier_sublist_repr) > 0)

    def test_get_schema(self):
        """Test that schema is properly generated."""
        registry = unreal.ToolsetRegistry
        schema_string = registry.get_toolset_json_schema(DemoPythonToolset.static_class())
        schema = json.loads(schema_string)
        self.assertEqual(schema['name'], DEMO_TOOLSET_NAME)
        self.assertEqual(schema['version'], '1.0')
        self.assertEqual(schema['description'], DemoPythonToolset.__doc__)
        expected_tool_schemas = {
            f'{DEMO_TOOLSET_NAME}.{DemoPythonToolset.hello_world.__name__}' : {
                'name': f'{DEMO_TOOLSET_NAME}.{DemoPythonToolset.hello_world.__name__}',
                'description': DemoPythonToolset.hello_world.__doc__.strip(),
                'inputSchema': {
                    'type': 'object',
                    'properties': {
                        'msg': {
                            'type': 'string'
                        }
                    },
                    'required': [
                        'msg'
                    ]
                },
                'outputSchema': {
                    'type': 'object',
                    'properties': {
                        'returnValue': {
                            'type': 'string'
                        }
                    },
                    'required': [
                        'returnValue'
                    ]
                }
            },
            f'{DEMO_TOOLSET_NAME}.{DemoPythonToolset.hello_many_worlds.__name__}' : {
                'name': f'{DEMO_TOOLSET_NAME}.{DemoPythonToolset.hello_many_worlds.__name__}',
                'description': DemoPythonToolset.hello_many_worlds.__doc__.strip(),
                'inputSchema': {
                    'type': 'object',
                    'properties': {
                        'msg': {
                            'type': 'string'
                        },
                        "world_count": {
                            "type": "integer",
                            "default": 42
                        }
                    },
                    'required': [
                        'msg'
                    ]
                },
                'outputSchema': {
                    'type': 'object',
                    'properties': {
                        'returnValue': {
                            'type': 'integer'
                        }
                    },
                    'required': [
                        'returnValue'
                    ]
                }
            },
            f'{DEMO_TOOLSET_NAME}.{DemoPythonToolset.hello_struct.__name__}' : {
                'name': f'{DEMO_TOOLSET_NAME}.{DemoPythonToolset.hello_struct.__name__}',
                'description': DemoPythonToolset.hello_struct.__doc__.strip(),
                'inputSchema': {
                    'type': 'object',
                    'properties': {
                        'test_input': {
                            'type': 'object',
                            'title': 'ToolsetTestInput',
                            'properties': {
                                'kind_of_input': {
                                    'type': 'string',
                                    'title': 'SomeKindOfEnum',
                                    'enum': [
                                        'ValueOne',
                                        'ValueTwo',
                                        'ValueThree'
                                    ]
                                },
                                'value_2': {
                                    'type': 'integer',
                                    'minimum': 0,
                                    'maximum': 50
                                },
                                'value_1': {
                                    'type': 'string',
                                    'description': 'Input string'
                                }
                            },
                            'required': [
                                'kind_of_input',
                                'value_2',
                                'value_1'
                            ]
                        }
                    },
                    'required': [
                        'test_input'
                    ]
                },
                'outputSchema': {
                    'type': 'object',
                    'properties': {
                        'returnValue': {
                            'type': 'object',
                            'title': 'ToolsetTestOutput',
                            'properties': {
                                'many_results': {
                                    'type': 'array',
                                    'items': {
                                        'type': 'string'
                                    }
                                },
                                'a_number': {
                                    'type': 'number'
                                },
                                'success': {
                                    'type': 'boolean'
                                }
                            },
                            'required': [
                                'many_results',
                                'a_number',
                                'success'
                            ]
                        }
                    },
                    'required': [
                        'returnValue'
                    ]
                }
            },
            f'{DEMO_TOOLSET_NAME}.{DemoPythonToolset.hello_void.__name__}' : {
                'name': f'{DEMO_TOOLSET_NAME}.{DemoPythonToolset.hello_void.__name__}',
                'description': DemoPythonToolset.hello_void.__doc__.strip(),
                'inputSchema': {
                    'type': 'object',
                },
            },
            f'{DEMO_TOOLSET_NAME}.{DemoPythonToolset.hello_list.__name__}' : {
                'name': f'{DEMO_TOOLSET_NAME}.{DemoPythonToolset.hello_list.__name__}',
                'description': DemoPythonToolset.hello_list.__doc__.strip(),
                'inputSchema': {
                    'type': 'object',
                    'properties': {
                        'input': {
                            'type': 'array',
                            'items': {
                                'type': 'string'
                            }
                        }
                    },
                    'required': [
                        'input'
                    ]
                },
                'outputSchema': {
                    'type': 'object',
                    'properties': {
                        'returnValue': {
                            'type': 'array',
                            'items': {
                                'type': 'string'
                            }
                        }
                    },
                    'required': [
                        'returnValue'
                    ]
                }
            },
            f'{DEMO_TOOLSET_NAME}.{DemoPythonToolset.hello_dict.__name__}' : {
                'name': f'{DEMO_TOOLSET_NAME}.{DemoPythonToolset.hello_dict.__name__}',
                'description': DemoPythonToolset.hello_dict.__doc__.strip(),
                'inputSchema': {
                    'type': 'object',
                    'properties': {
                        'input': {
                            'type': 'object',
                            'additionalProperties': {
                                'type': 'number'
                            }
                        }
                    },
                    'required': [
                        'input'
                    ]
                },
                'outputSchema': {
                    'type': 'object',
                    'properties': {
                        'returnValue': {
                            'type': 'object',
                            'additionalProperties': {
                                'type': 'number'
                            }
                        }
                    },
                    'required': [
                        'returnValue'
                    ]
                }
            },
            f'{DEMO_TOOLSET_NAME}.{DemoPythonToolset.hello_set.__name__}' : {
                'name': f'{DEMO_TOOLSET_NAME}.{DemoPythonToolset.hello_set.__name__}',
                'description': DemoPythonToolset.hello_set.__doc__.strip(),
                'inputSchema': {
                    'type': 'object',
                    'properties': {
                        'input': {
                            'type': 'array',
                            'items': {
                                'type': 'number'
                            },
                            'uniqueItems': True
                        }
                    },
                    'required': [
                        'input'
                    ]
                },
                'outputSchema': {
                    'type': 'object',
                    'properties': {
                        'returnValue': {
                            'type': 'array',
                            'items': {
                                'type': 'number'
                            },
                            'uniqueItems': True
                        }
                    },
                    'required': [
                        'returnValue'
                    ]
                }
            },
            f'{DEMO_TOOLSET_NAME}.{DemoPythonToolset.hello_optional.__name__}' : {
                'name': f'{DEMO_TOOLSET_NAME}.{DemoPythonToolset.hello_optional.__name__}',
                'description': DemoPythonToolset.hello_optional.__doc__.strip(),
                'inputSchema': {
                    'type': 'object',
                    'properties': {
                        'input': {
                            'type': 'number',
                            'default': None
                        }
                    },
                },
                'outputSchema': {
                    'type': 'object',
                    'properties': {
                        'returnValue': {
                            'type': 'number'
                        }
                    }
                }
            },
            f'{DEMO_TOOLSET_NAME}.{DemoPythonToolset.hello_object.__name__}' : {
                'name': f'{DEMO_TOOLSET_NAME}.{DemoPythonToolset.hello_object.__name__}',
                'description': DemoPythonToolset.hello_object.__doc__.strip(),
                'inputSchema': {
                    'type': 'object',
                    'properties': {
                        'input': {
                            'type': 'object',
                            'title': '/Script/CoreUObject.Object',
                            'description': 'Represents a reference to a UObject or UClass.',
                            'properties': {
                                'refPath': {
                                    'type': 'string',
                                    'description': 'The reference stored as a soft path string.'
                                },
                            },
                            'required': [
                                'refPath'
                            ]
                        }
                    },
                    'required': [
                        'input'
                    ]
                },
                'outputSchema': {
                    'type': 'object',
                    'properties': {
                        'returnValue': {
                            'type': 'object',
                            'title': '/Script/CoreUObject.Object',
                            'description': 'Represents a reference to a UObject or UClass.',
                            'properties': {
                                'refPath': {
                                    'type': 'string',
                                    'description': 'The reference stored as a soft path string.'
                                },
                            },
                            'required': [
                                'refPath',
                            ]
                        }
                    },
                    'required': [
                        'returnValue'
                    ]
                }
            },
        }
        self.maxDiff = None  # pylint: disable=invalid-name
        for tool_schema in schema['tools']:
            tool_name = tool_schema['name']
            expected_schema = expected_tool_schemas[tool_name]
            self.assertDictEqual(tool_schema, expected_schema,
                                 f'Mismatch in expected schema for {tool_name}')
